version: '3.8'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - SERVICE_TYPE=web
      - TESTING=${TESTING}

  celery:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    environment:
      - SERVICE_TYPE=celery

volumes:
  postgres_db_data:
